<a href="https://colab.research.google.com/github/Sandeep4118/colab-project/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Code

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
# Python list
a = [1,3,4,'hello',7.9]
a

[1, 3, 4, 'hello', 7.9]

In [ ]:
# Python array(only same data type allows)
arr

array([1, 2, 3, 4])

In [ ]:
b = np.array([1,2,4.5,'hello'])
b

array(['1', '2', '4.5', 'hello'], dtype='<U32')

In [ ]:
# in the array if there is any string then in output it converted everything into the string.

In [ ]:
# Vectors -> One dimensional(1D -> only single row)
# Matrix -> Multiple rows and coloums

np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 3d and so-on are called tensors.

In [ ]:
# Array Generation function

In [ ]:
# Generate all the number from 1 to 10
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# Generating Zeros
# 1d array
arr = np.zeros(6)
# arr

# 2d array
np.zeros((3,4))
# 3 rows and 4 coloumn


# Generating Ones
arr = np.ones(6)
# arr

# 2d array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Linear space
arr = np.linspace(1,5,3)
arr
# shows 3 element with equal spacing or differcing
np.linspace(0,1,50)


array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
# Random Generation function
# This is normalization where nos. are between 0 to 1
# 1d array random generation number
np.random.rand(5)

# 2d array random generation number
np.random.rand(5,2)

# Standilition where nos. are in between like(3 to -3).

np.random.randn(3)

np.random.randint(5)
np.random.randint(10,20,5)

array([12, 13, 16, 18, 14])

In [ ]:
# Array Attributes
arr = np.array([[1,2,3],
                [4,5,6],
                 [7,8,9]])
arr

arr.shape # int the output shows(3,3) where 3 rows and 3 columns
arr.size # mean how many elements are present
# arr.dtype # belongs to which datatypes


dtype('int64')

In [127]:
# Array Methods
arr

# finding the min element
arr.min()

# finding the max element
arr.max()

# give the sum of all elements
arr.sum()

# give the sum of each column or rows
# 1 -> Means Horizontal axis and 0 -> means of Vertical axis
np.sum(arr, axis=0)
# np.sum(arr, axis=1)

arr.mean()


# Standard devitation
# arr.std()

# argmax and armin provide the index of max element and min element.
# arr.argmax()
# arr.argmin()

np.float64(25.0)

In [ ]:
# Reshaping and Resizing

arr = np.arange(1,31)
arr


# reshape means converting the simple array into matrix and inside the reshape function there is an attribute name shape that shows size of matrix like 3X3 or 4X3 and the no. of elements must be present in your array like if there is an 3 x 3 matrix then the element must have 9.
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# Numpy Indexing and Slicing of Vectors
import numpy as np

arr = np.arange(11,21)
arr

# Slicing means removing the elements
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# it shows the row wise elements
arr[0]
arr[3]

array([16, 17, 18, 19, 20])

In [ ]:
# selecting the elements individually
arr[0,4]
arr[5,4]

np.int64(30)

In [ ]:
# slicing a group of element in 2d arrays, arr[rows,cols] means starting in row to end of rows ans same as it in coloumn
slice = arr[0:2, 1:3]
slice

array([[2, 3],
       [7, 8]])

In [ ]:
# Exercise
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
# slicing a coloumn
arr[:,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29]])

In [ ]:
# Boolean indexing
arr = np.arange(11,21)
arr

# getting all the even elements
bool_index = arr % 2 == 0
bool_index

arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [ ]:
# Array Operations

In [ ]:
import numpy as np


In [ ]:
# Arithmetic operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
# adding the elements but the no. of element in both array must be same
a1 + a2

# subtracting
a2 - a1

# multiplicationn
a1 * a2

# division
a1 / a2

# power
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
# Broadcasting means you want to perform some operation for all the element in the array and it work for all the element in a single pass
l = [10,20,30,40]
arr = np.array(l)
arr + 10
# adding 10 to all the elements in the array


array([20, 30, 40, 50])

In [ ]:
# Deep and Shallow copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice * 10

array([10, 20, 30, 40, 50])

In [ ]:
# whenever you are slicing any portion of an element in the array it doesn't effect to the original array but in list it will effect it.
a
# and this is the concept of shallow copy.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
# deep copy means original array also change when some part of the array will changes.

In [60]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [61]:
# Deep copy mean (a) will automatically change whenever the (b) change.
b = a
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
a
# see a will also change

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
# Matrix operation

In [66]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [67]:
A

array([[1, 2],
       [3, 4]])

In [68]:
B

array([[5, 6],
       [7, 8]])

In [70]:
# Mutliplication of matrix
A @ B

array([[19, 22],
       [43, 50]])

In [71]:
# another method
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [72]:
# transpose
A

array([[1, 2],
       [3, 4]])

In [73]:
A.T

array([[1, 3],
       [2, 4]])

In [74]:
# Advance Array Manipulation
# Stacking Array: in stacking array we use vector not matrix.
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [75]:
# there are three types of stacking(Vertical stack, Horizontal stack, Simple stack).
# This is the vertical stack
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
# This is the horizontal stack
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [78]:
# Splitting array

In [83]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [94]:
a = np.vsplit(c,4)
# equal division ma split kar skta hai bass

In [95]:
for i in a:
  print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


In [96]:
# Numpy Exercise

In [101]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [111]:
# Answer: Suduko is valid or not for rows
import numpy as np
b = np.sum(s,axis=1)
for i in b:
  if i != 45:
    print("Suduko is not valid")
    break
else:
  print("Suduko is valid")

Suduko is valid


In [113]:
# for coloumns axis = 0
c = np.sum(s,axis=0)
for i in c:
  if i != 45:
    print("Suduko is not valid")
    break
else:
  print("Suduko is valid")

Suduko is valid


In [119]:
# checking that each 3x3 has equal no. of pair or not like 1 to 9.
for i in range(0,9,3):
  for j in range(0,9,3):
    n = s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [120]:
# General Questions

In [179]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78], # Student 1
    [19,92,88], # Student 2
    [17,76,95], # Student 3
    [18,65,70], # Student 4
    [20,90,85]  # Student 5
])

In [180]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [181]:
# Find the average age of the students.
np.mean(data[:,:1])

np.float64(18.4)

In [182]:
# Extract Math marks of all students.
data[:5,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [183]:
# Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [184]:
# Increase Math marks of all students by 5.
data[:,1]+5
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [185]:
# Find how many student are younger then 19.
len(data[data[:,0]<19])

3

In [186]:
# Calculate the average marks in each subject (coloumn-wise mean).
# math or science
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [187]:
# Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [188]:
# Replacing all Science marks<75 with 0.
data[:,2][data[:,2]<75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])