<a href="https://colab.research.google.com/github/Sandeep4118/colab-project/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Code

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
# Python list
a = [1,3,4,'hello',7.9]
a

[1, 3, 4, 'hello', 7.9]

In [4]:
# Python array(only same data type allows)
arr

array([1, 2, 3, 4])

In [5]:
b = np.array([1,2,4.5,'hello'])
b

array(['1', '2', '4.5', 'hello'], dtype='<U32')

In [6]:
# in the array if there is any string then in output it converted everything into the string.

In [7]:
# Vectors -> One dimensional(1D -> only single row)
# Matrix -> Multiple rows and coloums

np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# 3d and so-on are called tensors.

In [9]:
# Array Generation function

In [11]:
# Generate all the number from 1 to 10
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
# Generating Zeros
# 1d array
arr = np.zeros(6)
# arr

# 2d array
np.zeros((3,4))
# 3 rows and 4 coloumn


# Generating Ones
arr = np.ones(6)
# arr

# 2d array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# Linear space
arr = np.linspace(1,5,3)
arr
# shows 3 element with equal spacing or differcing
np.linspace(0,1,50)


array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [38]:
# Random Generation function
# This is normalization where nos. are between 0 to 1
# 1d array random generation number
np.random.rand(5)

# 2d array random generation number
np.random.rand(5,2)

# Standilition where nos. are in between like(3 to -3).

np.random.randn(3)

np.random.randint(5)
np.random.randint(10,20,5)

array([12, 13, 16, 18, 14])

In [42]:
# Array Attributes
arr = np.array([[1,2,3],
                [4,5,6],
                 [7,8,9]])
arr

arr.shape # int the output shows(3,3) where 3 rows and 3 columns
arr.size # mean how many elements are present
# arr.dtype # belongs to which datatypes


dtype('int64')

In [57]:
# Array Methods
arr

# finding the min element
arr.min()

# finding the max element
arr.max()

# give the sum of all elements
arr.sum()

# give the sum of each column or rows
# 1 -> Means Horizontal axis and 0 -> means of Vertical axis
np.sum(arr, axis=0)
np.sum(arr, axis=1)

arr.mean()


# Standard devitation
arr.std()

# argmax and armin provide the index of max element and min element.
arr.argmax()
arr.argmin()

np.int64(8)

In [63]:
# Reshaping and Resizing

arr = np.arange(1,31)
arr


# reshape means converting the simple array into matrix and inside the reshape function there is an attribute name shape that shows size of matrix like 3X3 or 4X3 and the no. of elements must be present in your array like if there is an 3 x 3 matrix then the element must have 9.
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])